version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget-horizon-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
